import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { query } from './db.js';
import authRoutes from './routes/auth.js';
import workspaceRoutes from './routes/workspace.js';
import catalogRoutes from './routes/catalog.js';
import discountRoutes from './routes/discounts.js';
import quotationRoutes from './routes/quotations.js';
import approvalRoutes from './routes/approvals.js';
import moduleRoutes from './routes/modules.js';
import customerPortalRoutes from './routes/customerPortal.js';

const app = express();
const port = process.env.PORT || 4000;
app.use(cors({ origin: process.env.CLIENT_ORIGIN || 'http://localhost:5173' }));
app.use(express.json());
app.get('/api/health', async (_req, res) => { try { await query('SELECT 1'); res.json({ status: 'ok', database: 'connected' }); } catch { res.status(503).json({ status: 'degraded', database: 'unavailable' }); } });
app.use('/api/auth', authRoutes);
app.use('/api/workspaces', workspaceRoutes);
app.use('/api/catalog', catalogRoutes);
app.use('/api/discounts', discountRoutes);
app.use('/api/quotations', quotationRoutes);
app.use('/api/approvals', approvalRoutes);
app.use('/api/modules', moduleRoutes);
app.use('/api/customer-portal', customerPortalRoutes);
app.use((error, _req, res, _next) => { console.error(error); res.status(500).json({ message: 'Unexpected server error.' }); });
app.listen(port, () => console.log(`DealFlow360 API listening on http://localhost:${port}`));